plugins {
	id "multiloader-loader"
	id "fabric-loom"
}

archivesBaseName = "${mod_id}-fabric"
if (System.getenv().RELEASE_MODE == null) {
	version += "-SNAPSHOT"
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	mappings loom.layered() {
		officialMojangMappings()
		parchment("org.parchmentmc.data:parchment-${parchment_version}@zip")
	}
	modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
}

loom {
	mixin.defaultRefmapName = "${mod_id}.refmap.json"
	runs {
		client { programArgs "--width=1300", "--height=850" }
		configureEach {
			ideConfigGenerated = true
			runDir = "../run"
		}
	}
}
