plugins {
	id "multiloader-loader"
	id "fabric-loom"
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	mappings loom.layered() {
		officialMojangMappings()
		parchment("org.parchmentmc.data:parchment-${parchment_version}@zip")
	}
	modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
}

loom {
	mixin.defaultRefmapName = "${mod_id}.refmap.json"
	runs {
		client {
			programArgs "--width=1300", "--height=850"
			runDir = "../run"
		}
		server { runDir = "../runServer" }
		configureEach { ideConfigGenerated = true }
	}
}
