plugins {
	id "multiloader-xplat"
	// id "agency.highlysuspect.minivan"
	id "net.neoforged.moddev"
}

// minivan {
// 	version(minecraft_version) // TODO: can omit ()?
// }

neoForge {
	neoFormVersion = "26.1-1"
}

dependencies {
	compileOnly "org.spongepowered:mixin:0.8.7"
	compileOnly "io.github.llamalad7:mixinextras-common:0.5.3"
	compileOnly "org.ow2.asm:asm-commons:9.9.1"
}

configurations {
	xplatJava {
		canBeResolved = false
		canBeConsumed = true
	}
	xplatResources {
		canBeResolved = false
		canBeConsumed = true
	}
}

artifacts {
	xplatJava sourceSets.main.java.sourceDirectories.singleFile
	xplatResources sourceSets.main.resources.sourceDirectories.singleFile
}
