plugins {
	id "multiloader-xplat"
	// id "agency.highlysuspect.minivan"
	id "net.neoforged.moddev"
}

// minivan {
// 	version(minecraft_version) // TODO: can omit ()?
// }

neoForge {
	neoFormVersion = "1.21.10-20251010.172816"

	parchment {
		var parchment_components = parchment_version.split(":")
		mappingsVersion = parchment_components[1]
		minecraftVersion = parchment_components[0]
	}
}

dependencies {
	compileOnly "org.spongepowered:mixin:0.8.7"
	compileOnly "io.github.llamalad7:mixinextras-common:0.3.6"
}

configurations {
	xplatJava {
		canBeResolved = false
		canBeConsumed = true
	}
	xplatResources {
		canBeResolved = false
		canBeConsumed = true
	}
}

artifacts {
	xplatJava sourceSets.main.java.sourceDirectories.singleFile
	xplatResources sourceSets.main.resources.sourceDirectories.singleFile
}
