# Project
group=artemis.better_climbing
license=CC0-1.0
java_version=25

# Xplat
minecraft_version=26.1

# NeoForge
neoforge_version=26.1.0.1-beta

# Fabric
fabric_loader_version=0.18.5

# Mod
mod_name=Better Climbing
mod_id=better_climbing
mod_version=6
mod_author=artemis
mod_description=Improves a lot of things relating to climbing

# Mixin
mixin_min_version=0.8

# Gradle
org.gradle.jvmargs=-Xmx3G
