# Project
group=artemis.better_climbing
license=CC0-1.0
java_version=21

# Xplat
minecraft_version=1.21
parchment_version=1.21:2024.06.23

# NeoForge
neoforge_version=21.0.37-beta

# Fabric
fabric_loader_version=0.15.11

# Mod
mod_name=Better Climbing
mod_id=better_climbing
mod_version=4
mod_author=artemis
mod_description=Improves a lot of things relating to climbing

# Mixin
mixin_min_version=0.8

# Gradle
org.gradle.jvmargs=-Xmx3G
