plugins {
	id "multiloader-loader"
	id "net.neoforged.moddev"
}

neoForge {
	version = neoforge_version

	parchment {
		var parchment_components = parchment_version.split(":")
		mappingsVersion = parchment_components[1]
		minecraftVersion = parchment_components[0]
	}

	runs {
		client { client(); systemProperty "fml.earlyprogresswindow", "false" }
		server { server() }

		configureEach {
			// systemProperty('neoforge.enabledGameTestNamespaces', mod_id) // TODO: needed?
			ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
		}
	}

	mods {
		"${mod_id}" {
			sourceSet sourceSets.main
		}
	}
}

// mixin {
// 	add sourceSets.main, "${mod_id}.refmap.json"
// 	config "${mod_id}.xplat_mixins.json"
// }
