plugins {
	id "multiloader-loader"
	id "net.neoforged.moddev"
}

neoForge {
	version = neoforge_version

	runs {
		client {
			client()
			programArgument "--width=1300"
			programArgument "--height=850"
			gameDirectory = project.file("../run")
		}
		server {
			server()
			gameDirectory = project.file("../runServer")
		}
		configureEach {
			ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
		}
	}

	mods {
		"${mod_id}" {
			sourceSet sourceSets.main
		}
	}
}
